name: Arbitrary Commnad Injection When Creating New Issue

on:
  issues:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "New issue: ${{ github.event.issue.title }}"
          echo "Secret: ${{ secrets.GITHUB_TOKEN }}"
          echo "Secret: ${{ secrets.GITHUB_TOKEN }}" | hc -C
          echo "Secret: ${{ secrets.GITHUB_TOKEN }}" | hexdump
          echo "$MY_SECRET" | base64
