name: Arbitrary Commnad Injection When Creating New Issue

on:
  issues:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "New issue: ${{ github.event.issue.title }}"
          echo "Secret: ${{ secrets.GITHUB_TOKEN }}"
          echo "${{ secrets.MY_SECRET }}" | base64
          echo "Secret: ${{ secrets.GITHUB_TOKEN }}" | hc -C    
